pub_cache:
  folder: ~/.pub-cache

task:
  name: Run analyzer
  container:
    image: cirrusci/flutter:stable

  analyze_script: flutter analyze

task:
  name: Run tests
  container:
    image: cirrusci/flutter:stable
  test_script: flutter test

task:
  name: Build example app (Android)
  container:
    image: cirrusci/flutter:stable
  build_script:
    - cd example
    - flutter build apk --debug

task:
  name: Build example app (iOS)
  osx_instance:
    image: big-sur-xcode-13
  build_script:
    - cd example
    - flutter build ios --no-codesign --debug