name: siri_wave
description: A Flutter package to create beautiful waveforms like in Siri.
version: 0.3.0
repository: https://github.com/halildurmus/siri_wave

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
